name: Manual Trigger Example

on:
  workflow_dispatch: ~

jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Environment
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
